### ISSUE TITLE
Unable to drag the window while the command bar is enabled

### ISSUE THREAD

**Issue by aappaapp** [voylin/GoZen#41] opened 2023-08-24 00:12 UTC
### Version or branch

ec8bfe15015018650ab51ff9bd52fc0dfa1e7c21

### Operating system

Windows

### Bug behaviour

Unable to drag the window (or press anything) while the command bar is enabled.

### Expected behaviour

I should be able to drag the window when it is enabled.

### Steps to reproduce

1. Open the command bar (using `/`)
2. Try dragging the window (you can't)

### Other informations

I think the command bar should be hidden when the user presses something else. (And maybe add a semi-transparent background to indicate you can't press other things)

**Comment by voylin** [comment] 2023-08-24 00:37
I think I know what the issue is, I'll have to put it on the window content itself, small fix which I'll fix in the next push ;)

**Comment by voylin** [comment] 2023-08-26 00:07
Got fixed in f67ba09, however everything is kind of broken right now because of the file explorer which I am doing improvements on. So testing won't be possible until I got that sorted out which may happen later today or in the next couple of days.

**Closed by voylin** 2023-08-26 00:07 UTC
